const SITE_ORIGIN = "http://localhost:3000";
const MINUTES_IN_SECONDS = 10 * 60;
const DAYS_IN_SECONDS = 15 * (60 * 60);
const ACCESS_TOKEN_ISSUER = "EDU_MANAGER_PRO_ACCESS";
const REFRESH_TOKEN_ISSUER = "EDU_MANAGER_PRO_REFRESH";

export {
  SITE_ORIGIN,
  MINUTES_IN_SECONDS,
  DAYS_IN_SECONDS,
  ACCESS_TOKEN_ISSUER,
  REFRESH_TOKEN_ISSUER,
};
